config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
    get 'signin', to: 'devise/sessions#new'
    delete 'signout', to: 'devise/sessions#destroy'
    get 'signup', to: 'devise/registrations#new'
  end

  get 'users/:username', to: 'users#show', as: 'user'

  resources :foods do
    member do
      post 'vote', to: 'votes#create'
      delete 'unvote', to: 'votes#destroy'
    end
  end
  resources :tweets


  root 'foods#index'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_authorization.rb
class AdminAuthorization < ActiveAdmin::AuthorizationAdapter
  def authorized?(action, subject = nil)
    user && user.admin?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user

  validates :user, presence: true
  validates :brand, :name, :calories, presence: true
  validates :calories, numericality: true

  acts_as_votable
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  has_many :tweets
  has_many :foods

  validates :username, presence: true, uniqueness: true, length: { minimum: 6 }
  validates :name, presence: true

  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def access_denied(exception)
    redirect_to root_path, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
    @food = Food.find(params[:id])
  end

  # GET /foods/new
  def new
    @food = current_user.foods.new
  end

  # GET /foods/1/edit
  def edit
    @food = current_user.foods.find(params[:id])
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = current_user.foods.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    @food = current_user.foods.find(params[:id])
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food = current_user.foods.find(params[:id])
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_food
    #   @food = Food.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:user_id, :brand, :name, :calories)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  # GET /tweets
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  def show
    @tweet = Tweet.find(params[:id])
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.new
  end

  # GET /tweets/1/edit
  def edit
    @tweet = current_user.tweets.new(tweet_params)
  end

  # POST /tweets
  def create
    @tweet = current_user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to @tweet, notice: 'Tweet was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tweets/1
  def update
    @tweet = current_user.tweets.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'Tweet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet = current_user.tweets.find(params[:id])
    @tweet.destroy
    edirect_to tweets_url, notice: 'Tweet was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_tweet
    #   @tweet = current_user.tweets.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:user_id, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(username: params[:username])
    @foods = @user.nil? ? [] : @user.foods
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!

  def create
    item = Food.find(params[:id])
    item.liked_by current_user
    redirect_to foods_path, notice: "You successfully voted for a food"
  end

  def destroy
    item = Food.find(params[:id])
    item.unliked_by current_user
    redirect_to foods_path, notice: "You successfully unvoted for a food"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_form.html.erb
<%= form_with(model: food, local: true) do |form| %>
  <% if food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :brand %>
    <%= form.text_area :brand, id: :food_brand, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_area :name, id: :food_name, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :calories %>
    <%= form.number_field :calories, id: :food_calories, class: "form-control"%>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary"    %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<div class="container">
  <h1>Editing Food</h1>

  <%= render 'form', food: @food %>

  <%= link_to 'Show', @food %> |
  <%= link_to 'Back', foods_path %>
</div>

app/views/foods/index.html.erb
<div class="container">
  <h1>Foods</h1>
  <% if user_signed_in? %>
    <h2 class="text-center"><%= link_to current_user.username, user_path(current_user.username)%></h2>
  <% else %>
    <h2 class="text-center"><%= link_to 'Sign Up Now!', signup_path %></h2>
  <% end %>

  <table class="table">
    <thead>
      <tr>
        <th>Votes</th>
        <th>Brand</th>
        <th>Name</th>
        <th>Calories</th>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td><%= food.votes_for.up.size %></td>
          <td><%= food.brand %></td>
          <td><%= food.name %></td>
          <td><%= food.calories %></td>
          <td><%= link_to 'Show', food %></td>

          <% if user_signed_in? && (current_user.voted_up_on? food) %>
            <td><%= link_to 'Unvote', unvote_food_path(food), method: :delete %></td>
          <% else %>
            <td><%= link_to 'Vote', vote_food_path(food), method: :post %></td>
          <% end %>
          <% if food.user = current_user %>
            <td><%= link_to 'Edit', edit_food_path(food) %></td>
            <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <% if user_signed_in? %>
    <%= link_to 'New Food', new_food_path %>
  <% end %>
</div>

app/views/foods/new.html.erb
<div class="container">
  <h1>New Food</h1>

  <%= render 'form', food: @food %>

  <%= link_to 'Back', foods_path %>

</div>

app/views/foods/show.html.erb
<div class="container">
  <p>
    <strong>User:</strong>
    <%= @food.user %>
  </p>

  <p>
    <strong>Brand:</strong>
    <%= @food.brand %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= @food.name %>
  </p>

  <p>
    <strong>Calories:</strong>
    <%= @food.calories %>
  </p>

  <% if @food.user == current_user %>
    <%= link_to 'Edit', edit_food_path(@food) %>
  <% end %>
  <%= link_to 'Back', foods_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>One Month Rails Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Navigation Bar -->

    <nav class="navbar navbar-inverse navbar-toggleable-sm bg-inverse">
      <%= link_to "One Month Rails", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Contact", "#", class: "nav-link" %></li>
          <% if user_signed_in? %>
            <li class="nav-item"><%= link_to "Sign Out", signout_path, method: :delete, class: "nav-link" %></li>
          <% else %>
            <li class="nav-item"><%= link_to "Sign Up", signup_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "Sign In", signin_path, class: "nav-link" %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <!-- <nav class="navbar navbar-inverse navbar-toggleable-sm bg-inverse">
      <div class="container">
        <%= link_to "One Month Rails", root_path, class: "navbar-brand" %>
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Contact", "#", class: "nav-link" %></li>
        </ul>
      </div>
    </nav> -->

    <!-- Flash Messages -->
    <% flash.each do |name, message| %>
      <%= content_tag(:div, message, class:"alert alert-info #{name}") %>
    <% end %>

    <!-- Page Content -->
    <%= yield %>

    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>© 2016 One Month</p>
        </center>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>About us</h1>
        <p>This is the sample project I built for <a href="https://onemonthrails.com">One Month Rails</a>.</p>
    </div>
</div>

app/views/pages/contact.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>Contact us</h1>
        <p>Give me a call : 04XX XXX XXX</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et suscipit tellus. Sed felis velit, imperdiet eu felis nec, posuere ullamcorper nulla. Etiam in fermentum mi. Integer tempor ac nisl in iaculis. Nullam scelerisque lectus ac iaculis vehicula. Duis lacinia orci quis rhoncus porttitor. Cras sed ultricies odio.

        <p>Curabitur non urna semper, tincidunt elit a, maximus elit. Integer egestas neque a eros congue fringilla. Vivamus vestibulum aliquam ipsum, ut iaculis elit ultricies sed. Integer elementum velit lacus, vitae vehicula dui malesuada ut. Proin condimentum mattis libero ac malesuada. Nulla ac ipsum ultricies, euismod sapien tempor, faucibus urna. Nulla velit ipsum, tempus ut dapibus ac, imperdiet vitae dui. Phasellus fermentum et diam aliquam malesuada. Proin rutrum dapibus lacus vel pellentesque.<p>

        <p>Duis malesuada magna et augue malesuada rhoncus. Aliquam tincidunt lorem ultricies velit semper, sit amet sagittis ipsum faucibus. Curabitur elit dolor, ornare id dolor ornare, congue imperdiet sem. Vestibulum euismod dignissim posuere. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce id lobortis dolor. Donec cursus pharetra sapien, a commodo mi malesuada at. Nulla in lorem quis est iaculis facilisis nec ut neque. Nulla faucibus lacus id dictum accumsan. Sed sed est neque. Ut consectetur, metus quis ullamcorper porta, massa mi venenatis felis, sed vehicula lacus diam et leo. Morbi non molestie dolor. Duis porttitor semper vehicula. Maecenas ultrices tellus vitae eros semper, non sodales velit consequat. Nullam vitae magna sed mauris maximus pellentesque sit amet sed mauris. Sed ex metus, efficitur vel mollis eu, tempus sit amet nunc.</p>

    </div>
</div>

app/views/pages/home.html.erb
<% if user_signed_in? %>
  <div class="jumbotron jumbotron-home">
    <div class="container">
        <h1>Welcome Back!</h1>
    </div>
  </div>
<% else %>
  <div class="jumbotron jumbotron-home">
    <div class="container">
        <h1>Welcome to my website!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <%= link_to "Learn more »", "#", class: "btn btn-primary btn-lg" %>
    </div>
  </div>
  <div class="container">
      <div class="row">
          <div class="col-md-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
          </div>
          <div class="col-md-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
          </div>
          <div class="col-md-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
          </div>
      </div>
  </div>
<% end %>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, id: :tweet_content, class: "form-control" %>
  </div>
  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/tweets/edit.html.erb
<div class="container">
  <h1>Editing Tweet</h1>

  <%= render 'form', tweet: @tweet %>

  <%= link_to 'Show', @tweet %> |
  <%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="card">
        <div class="card-block">
          <h4 class="card-title">Your Account</h4>
          <p class="card-text"><%= current_user.username %></p>
        </div>
      </div>
    </div>
    <div class="col-md-8">
          <% if user_signed_in? %>
            <%= link_to 'New Tweet', new_tweet_path %>
          <% end %>
          <ul class="list-group">
            <% @tweets.each do |tweet| %>
              <%= link_to tweet, class: "list-group-item list-group-item-action" do %>
                <h5 class="list-group-item-heading"><%= tweet.user.username %></h5>
                <p class="list-group-item-text"><%= tweet.content %></p>
                <p class="list-group-item-text">
                  <% if tweet.user == current_user %>
                    <%= link_to 'Edit', edit_tweet_path(tweet) %>
                    <%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %>
                  <% end %>
                </p>
              <% end %>
            <% end %>
          </ul>
    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<div class="container">
  <h1>New Tweet</h1>

  <%= render 'form', tweet: @tweet %>

  <%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/show.html.erb
<div class="container">
  <div class="row">
    <div class="offset-md-2 col-md-8">
      <div class="card">
        <div class="card-block">
          <h4 class="card-title"><%= @tweet.user %></h4>
          <p class="card-text"><%= @tweet.content %></p>
          <% if @tweet.user == current_user %>
            <%= link_to 'Edit', edit_tweet_path(@tweet), class: "card-link" %>
          <% end %>
          <%= link_to 'Back', tweets_path, class: "card-link" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <% unless @user.nil? %>
    <h1><%= @user.username %></h1>
    <p><%= @user.name %></p>
  <% end %>

  <h2 class="text-center">My Foods</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Brand</th>
        <th>Name</th>
        <th>Calories</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td><%= food.brand %></td>
          <td><%= food.name %></td>
          <td><%= food.calories %></td>
          <td><%= link_to 'Show', food %></td>
          <% if food.user = current_user %>
            <td><%= link_to 'Edit', edit_food_path(food) %></td>
            <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>